apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    {{- with .Values.nginx.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  containers:
    - name: {{ .Values.nginx.spec.containers.name }}
      image: {{ .Values.nginx.spec.containers.image }}
      ports:
        - containerPort: {{ .Values.nginx.spec.containers.ports.containerPort }}
          protocol: {{ .Values.nginx.spec.containers.ports.protocol }}
      volumeMounts:
        - name: {{ .Values.nginx.spec.containers.volumeMount.name }}
          mountPath: {{ .Values.nginx.spec.containers.volumeMount.mountPath }}
  volumes:
    - name: {{ .Values.nginx.spec.volumes.name }}
      persistentVolumeClaim:
        claimName: {{ .Values.nginx.spec.volumes.persistentVolumeClaim.claimName }}
