apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storageSize }}
  volumeMode: {{ .Values.persistentVolume.volumeMode }}
  accessModes:
    - {{ .Values.persistentVolume.accessModes }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  mountOptions:
    {{- range .Values.persistentVolume.mountOptions }}
    - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.persistentVolumeReclaimPolicy }}
  csi:
    driver: {{ .Values.persistentVolume.csi.driver }}
    volumeHandle: {{ .Values.persistentVolume.csi.volumeHandle }}
    volumeAttributes:
      bucketName: {{ .Values.persistentVolume.csi.bucketName }}
