apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: {{ .Values.storageClass.provisioner }}  # Provisioner for AWS S3
parameters:
  type: {{ .Values.storageClass.parameters.type }}
